idp:
  version: @project.version@
  idpSig:
    fileName: classpath:authenticatorModule_idpServer.p12
    keyId: idpSig
  idpEnc:
    fileName: classpath:idp-fd-sig-refimpl-2.p12
    keyId: idpEnc
  discSig:
    fileName: classpath:idp-fd-sig-refimpl-3.p12
    keyId: discSig
  symmetricEncryptionKey: "geheimerSchluesselDerNochGehashtWird"
  redirectUri: http://redirect.gematik.de/erezept
  defaultLocale: US
  debug:
    requestLogging: true
  subjectSaltValue: fkdlsjaviaen4evdsnavaew4vcxo
  blockedClientSystems:
    - "blocked_user_agent"
  productTypeDisplayString: "IDP"
  tokenFlowMdResource: "classpath:tokenFlow.md"
caching:
  discoveryDocument:
    cacheControl: "max-age=300"
logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    de.gematik: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    httptrace:
      enabled: true
spring:
  liquibase:
    enabled: true
    change-log: "classpath:db/changelog/idp-changelog-master.xml"
  datasource:
    url: "jdbc:h2:mem:idp;INIT=CREATE SCHEMA IF NOT EXISTS IDP;"
    driver-class-name: org.h2.Driver
    username: root
    password: idp
    liquibaseSchemaName: IDP
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
