idp:
  version: @project.version@
  authKey:
    fileName: classpath:authenticatorModule_idpServer.p12
    keyId: authKey
  tokenKey:
    fileName: classpath:authenticatorModule_idpServer.p12
    keyId: tokenKey
  discoveryKey:
    fileName: classpath:authenticatorModule_idpServer.p12
    keyId: discoveryKey
  symmetricEncryptionKey: "geheimerSchluesselDerNochGehashtWird"
  redirectUri: http://redirect.gematik.de/erezept
  defaultLocale: US
  debug:
    requestLogging: true
  subjectSaltValue: fkdlsjaviaen4evdsnavaew4vcxo
  blockedClientSystems:
    - "blocked_user_agent"
logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    de.gematik: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    httptrace:
      enabled: true
spring:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/idp-changelog-master.xml
  datasource:
    url: jdbc:h2:mem:idp;INIT=CREATE SCHEMA IF NOT EXISTS IDP;
    driver-class-name: org.h2.Driver
    username: root
    password: idp
    liquibaseSchemaName: IDP
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true